name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is shipping the next version 🚀
on: [push]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - name: Find directories
        id: set-matrix
        shell: bash
        run: |
          # 1. Finde Ordner
          # 2. Sortiere sie (wichtig für Konsistenz)
          # 3. jq erstellt ein Array und entfernt ALLES, was leer ist (length > 0)
          PROJECTS=$(find . -maxdepth 1 -mindepth 1 -type d -not -path '*/.*' -printf '%P\n' | sort | jq -R -s -c 'split("\n") | map(select(length > 0))')

          echo "Raw Projects: $PROJECTS"

          # Fallback: Wenn das Ergebnis leer ist oder nur "[]", setze explizit ein leeres Array
          if [ -z "$PROJECTS" ] || [ "$PROJECTS" == "[]" ]; then
             echo "matrix=[]" >> $GITHUB_OUTPUT
          else
             echo "matrix=$PROJECTS" >> $GITHUB_OUTPUT
          fi

  lint:
    needs: discover
    runs-on: ubuntu-latest
    if: ${{ needs.discover.outputs.matrix != '[]' && needs.discover.outputs.matrix != '' }}
    strategy:
          fail-fast: false # Wenn ein Projekt fehlschlägt, laufen die anderen weiter
          matrix:
            project: ${{ fromJson(needs.discover.outputs.matrix) }}

    name: Check ${{ matrix.project }}
    defaults:
          run:
            working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          if [ -f pyproject.toml ]; then
            uv sync
          elif [ -f requirements.txt ]; then
            uv venv
            uv pip install -r requirements.txt
          else
            echo "No dependencies found in ${{ matrix.project }}, skipping install."
          fi

      - name: Activate virtual environment
        run: |
          if [ -d ".venv" ]; then
            echo "$PWD/.venv/bin" >> $GITHUB_PATH
          fi

      - name: Run tests
        run: |
          if command -v pytest > /dev/null 2>&1; then
            pytest --maxfail=1 --disable-warnings -q
          else
            echo "Pytest not installed in ${{ matrix.project }}. Skipping tests."
          fi

      - name: Run linting
        run: |
          if command -v ruff > /dev/null 2>&1; then
            echo "Ruff is installed. Running checks..."
            ruff check .
          else
            echo "Ruff is NOT installed in ${{ matrix.project }}. Skipping linting."
          fi
